# Generated by Django 2.2.13 on 2021-02-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_time', models.DateTimeField(blank=True, null=True)),
                ('province', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('confirm', models.IntegerField(blank=True, null=True)),
                ('confirm_add', models.IntegerField(blank=True, null=True)),
                ('heal', models.IntegerField(blank=True, null=True)),
                ('dead', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'details',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('ds', models.DateTimeField(primary_key=True, serialize=False)),
                ('confirm', models.IntegerField(blank=True, null=True)),
                ('confirm_add', models.IntegerField(blank=True, null=True)),
                ('suspect', models.IntegerField(blank=True, null=True)),
                ('suspect_add', models.IntegerField(blank=True, null=True)),
                ('heal', models.IntegerField(blank=True, null=True)),
                ('heal_add', models.IntegerField(blank=True, null=True)),
                ('dead', models.IntegerField(blank=True, null=True)),
                ('dead_add', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='History_China',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateId', models.DateTimeField(blank=True, null=True)),
                ('confirmedCount', models.IntegerField(blank=True, null=True)),
                ('confirmedIncr', models.IntegerField(blank=True, null=True)),
                ('curedCount', models.IntegerField(blank=True, null=True)),
                ('curedIncr', models.IntegerField(blank=True, null=True)),
                ('currentConfirmedCount', models.IntegerField(blank=True, null=True)),
                ('currentConfirmedIncr', models.IntegerField(blank=True, null=True)),
                ('deadCount', models.IntegerField(blank=True, null=True)),
                ('deadIncr', models.IntegerField(blank=True, null=True)),
                ('suspectedCount', models.IntegerField(blank=True, null=True)),
                ('suspectedCountIncr', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_china',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='History_China_Prov',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateId', models.DateTimeField(blank=True, null=True)),
                ('provinceName', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmedCount', models.IntegerField(blank=True, null=True)),
                ('confirmedIncr', models.IntegerField(blank=True, null=True)),
                ('curedCount', models.IntegerField(blank=True, null=True)),
                ('curedIncr', models.IntegerField(blank=True, null=True)),
                ('currentConfirmedCount', models.IntegerField(blank=True, null=True)),
                ('currentConfirmedIncr', models.IntegerField(blank=True, null=True)),
                ('deadCount', models.IntegerField(blank=True, null=True)),
                ('deadIncr', models.IntegerField(blank=True, null=True)),
                ('suspectedCount', models.IntegerField(blank=True, null=True)),
                ('suspectedCountIncr', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_china_prov',
                'managed': True,
            },
        ),
    ]
