# Generated by Django 2.2.13 on 2021-02-22 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cov', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_Shanghai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateId', models.DateTimeField(blank=True, null=True)),
                ('provinceName', models.CharField(blank=True, max_length=50, null=True)),
                ('provinceCode', models.CharField(blank=True, max_length=50, null=True)),
                ('confirmedCount', models.IntegerField(blank=True, null=True)),
                ('confirmedIncr', models.IntegerField(blank=True, null=True)),
                ('curedCount', models.IntegerField(blank=True, null=True)),
                ('curedIncr', models.IntegerField(blank=True, null=True)),
                ('currentConfirmedCount', models.IntegerField(blank=True, null=True)),
                ('currentConfirmedIncr', models.IntegerField(blank=True, null=True)),
                ('deadCount', models.IntegerField(blank=True, null=True)),
                ('deadIncr', models.IntegerField(blank=True, null=True)),
                ('suspectedCount', models.IntegerField(blank=True, null=True)),
                ('suspectedCountIncr', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history_shanghai',
                'managed': True,
            },
        ),
    ]
